# This file is part of the Sylius package.
# (c) Sylius Sp. z o.o.

sylius_shop_product_index:
    path: /{slug}
    methods: [GET]
    defaults:
        _controller: sylius.controller.product::indexAction
        _sylius:
            template: "@SyliusShop/product/index.html.twig"
            grid: sylius_shop_product
    requirements:
        slug: .+(?<!/)
