#!/bin/bash

if [ "${TRAVIS_PHP_VERSION}" != "7.0" ]; then
    exit 0
fi

if [ ! -f $SYLIUS_CACHE_DIR/memcached.so ]; then
    git clone -b php7 https://github.com/php-memcached-dev/php-memcached.git php-memcached
    cd php-memcached

    phpize
    ./configure --disable-memcached-sasl
    make

    cp modules/memcached.so "${SYLIUS_CACHE_DIR}"
fi

EXTENSIONS_DIR="$(php -i | grep extension_dir | head -n 1 | awk '{ print $5 }')"

cp "${SYLIUS_CACHE_DIR}/memcached.so" "${EXTENSIONS_DIR}"
