#!/bin/bash

if [ $TRAVIS_PHP_VERSION != "7.0" ]; then
    exit 0
fi

if [ ! -f $SYLIUS_CACHE_DIR/memcached.so ]; then
    git clone -b php7 https://github.com/php-memcached-dev/php-memcached.git php-memcached
    cd php-memcached

    phpize
    ./configure
    make

    cp modules/memcached.so $SYLIUS_CACHE_DIR
fi

cp $SYLIUS_CACHE_DIR/memcached.so `php -i | grep extensions | awk '{ print $5 }'`
