#!/usr/bin/env bash

EXIT_CODE=0

bin/behat --strict -f progress -p cached ; EXIT_CODE=$?

if [[ $EXIT_CODE -eq 1 ]]; then
    bin/behat --strict -f progress -p cached --rerun; EXIT_CODE=$?
fi;

exit $EXIT_CODE