#!/usr/bin/env bash

INITIAL_PWD=`pwd`
EXIT_CODE=0

for dir in `etc/travis/find-packages`; do
    echo "Validating Composer configuration at $dir..."

    cd "$dir"
    composer validate --strict || EXIT_CODE=$?
done

cd $INITIAL_PWD
exit $EXIT_CODE
