#!/usr/bin/env bash

source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/lib/common.lib.sh"

validate_package() {
    echo -e "\e[1mValidating:\e[20m \e[33;1m$(get_package_name "$1")\e[0;20m"
    run_command "composer validate --ansi --strict $1/composer.json"
}

if [ -z "$1" ]; then
    echo "Usage: $0 <absolute package path>"
    exit 1
fi

validate_package "$1"
