.. raw:: html

    <ul class="simple">
    <li><p><a class="reference internal" href="products/products.html"><span class="doc">Products</span></a></p></li>
    <li><p><a class="reference internal" href="products/product_reviews.html"><span class="doc">Product Reviews</span></a></p></li>
    <li><p><a class="reference internal" href="products/product_associations.html"><span class="doc">Product Associations</span></a></p></li>
    <li><p><a class="reference internal" href="products/attributes.html"><span class="doc">Attributes</span></a></p></li>
    <li><p><a class="reference internal" href="products/pricing.html"><span class="doc">Pricing</span></a></p></li>
    <li><p><a class="reference internal" href="products/taxons.html"><span class="doc">Taxons</span></a></p></li>
    <li><p><a class="reference internal" href="products/inventory.html"><span class="doc">Inventory</span></a></p></li>
    <li><p><a class="reference internal plus-feature" href="products/multi_source_inventory.html"><span class="doc">Multi-Source Inventory</span></a></p></li>
    <li><p><a class="reference internal" href="products/search.html"><span class="doc">Search</span></a></p></li>
    </ul>
