call bin\behat --strict -f progress -s account
call bin\behat --strict -f progress -s addressing
call bin\behat --strict -f progress -s cart
call bin\behat --strict -f progress -s currencies
call bin\behat --strict -f progress -s dashboard
call bin\behat --strict -f progress -s homepage
call bin\behat --strict -f progress -s inventory
call bin\behat --strict -f progress -s localization
call bin\behat --strict -f progress -s oauth
call bin\behat --strict -f progress -s reports
call bin\behat --strict -f progress -s taxonomy
