imports:
    - { resource: "@SyliusCoreBundle/Resources/config/app/config.yml" }
    - { resource: "@SyliusPayumBundle/Resources/config/app/config.yaml" }
    - { resource: "@SyliusShopBundle/Resources/config/app/config.yml" }
    - { resource: "@SyliusApiBundle/Resources/config/app/config.yaml" }
    - { resource: "@SyliusAdminBundle/Resources/config/app/config.yml" }
    - { resource: "../parameters.yaml" }

parameters:
    sylius_core.public_dir: '%kernel.project_dir%/public'
    sylius_core.grids_configuration:
        use_legacy_config: '%env(bool:TEST_SYLIUS_USE_LEGACY_GRID_CONFIG)%'

sylius_core:
    routing:
        bc_layer:
            enabled: true
            routes:
                admin_product:
                    enabled: false

sylius_api:
    enabled: true

sylius_shop:
    product_grid:
        include_all_descendants: true

sylius_resource:
    routing_path_bc_layer: false
    mapping:
        imports:
            - "%kernel.project_dir%/src/Sylius/Bundle/AdminBundle/Resources/config/app/sylius/resources/product.php"
