framework:
    secret: '%env(APP_SECRET)%'
    form:
        enabled: true
    csrf_protection: true
    http_method_override: true
    property_info:
        with_constructor_extractor: false
    session:
        handler_id: ~
