@managing_products
Feature: Editing product's slug
    In order to manage access path to product page
    As an Administrator
    I want to be able to edit product's slug
    
    Background:
        Given the store is available in "English (United States)"
        And I am logged in as an administrator

    @ui @todo @javascript
    Scenario: Creating product with autogenerated slug
        Given I want to create a new simple product
        When I specify its code as "BOARD_MANSION_OF_MADNESS"
        And I name it "Mansion of Madness" in "English (United States)"
        And I set its price to "$100.00"
        And I add it
        Then I should be notified that it has been successfully created
        And the product "Mansion of Madness" should appear in the shop
        And product "Mansion of Madness" slug should be "mansion-of-madness"

    @ui
    Scenario: Creating product with custom slug
        Given I want to create a new simple product
        When I specify its code as "BOARD_MANSION_OF_MADNESS"
        And I name it "Mansion of Madness" in "English (United States)"
        And I set its price to "$100.00"
        And I set its slug to "mom-board-game"
        And I add it
        Then I should be notified that it has been successfully created
        And the product "Mansion of Madness" should appear in the shop
        And product "Mansion of Madness" slug should be "mom-board-game"

    @ui
    Scenario: Seeing disabled slug field when editing product
        Given the store has a product "Mansion of Madness"
        When I want to modify this product
        Then the slug field should be disabled

    @ui @todo @javascript
    Scenario: Prevent from editing slug while changing product name
        Given the store has a product "Mansion of Madness"
        When I want to modify this product
        And I rename it to "Mansion of Madness: Second Edition" in "English (United States)"
        And I save my changes
        Then I should be notified that it has been successfully edited
        And this product name should be "Mansion of Madness: Second Edition"
        And product "Mansion of Madness" slug should still be "mansion-of-madness"

    @ui @todo @javascript
    Scenario: Automatically changing product's slug while editing product's name
        Given the store has a product "Mansion of Madness"
        When I want to modify this product
        And I enable slug modification
        And I rename it to "Small World" in "English (United States)"
        And I save my changes
        Then I should be notified that it has been successfully edited
        And this product name should be "Small World"
        And product "Mansion of Madness" slug should still be "small-world"

    @ui @todo @javascript
    Scenario: Manually changing product's slug while editing product's name
        Given the store has a product "Mansion of Madness"
        When I want to modify this product
        And I enable slug modification
        And I rename it to "Small World" in "English (United States)"
        And I set its slug to "small-world-board-game"
        And I save my changes
        Then I should be notified that it has been successfully edited
        And this product name should be "Small World"
        And product "Mansion of Madness" slug should still be "small-world-board-game"
