ux_icons:
    iconify:
        enabled: false
    icon_dir: '%kernel.project_dir%/src/Sylius/Bundle/UiBundle/Resources/assets/icons'
    ignore_not_found: false
    default_icon_attributes:
        'class': 'icon'
