sylius_admin_shop_user_delete:
    path: /{id}/delete
    methods: [DELETE]
    condition: "context.isSyliusRoutingBcLayerEnabled('admin_shop_user')"
    defaults:
        _controller: sylius.controller.shop_user::deleteAction
        _sylius:
            section: admin
            redirect:
                route: sylius_admin_customer_show
                parameters: { id: $customerId }
            permission: true
