Vagrant.configure("2") do |config|
  config.vm.box = "puphpet/ubuntu1404-x64"

    config.ssh.forward_agent = true

  # VMWare Workstation
  config.vm.provider "vmware_workstation" do |v, override|
    override.vm.network "private_network", ip: "113.0.0.10"
    v.memory = 1024
  end


  config.vm.synced_folder "./../", "/var/www/sylius", id: "vagrant-root", type: "nfs", mount_options: ['rw', 'vers=3', 'tcp', 'fsc' ,'actimeo=2']


  config.vm.provision :shell do |shell|
    shell.path = "bootstrap.sh"
  end

  config.vm.provision :puppet do |puppet|
    puppet.manifests_path = "manifests"
    puppet.options = ['--verbose']
  end
end
