.. raw:: html

    <ul class="simple">
    <li><p><a class="reference internal" href="customer_and_shopuser.html"><span class="doc">Customer and ShopUser</span></a></p></li>
    <li><p><a class="reference internal plus-feature" href="customer_pools.html"><span class="doc">Customer Pools</span></a></p></li>
    <li><p><a class="reference internal" href="adminuser.html"><span class="doc">AdminUser</span></a></p></li>
    <li><p><a class="reference internal" href="addresses/index.html"><span class="doc">Addresses</span></a></p></li>
    </ul>