sylius_twig_hooks:
    hooks:
        'sylius_admin.base#metatags':
            theme:
                template: '@SyliusAdmin/shared/layout/base/theme.html.twig'
                priority: 100
            metatags:
                template: '@SyliusAdmin/shared/layout/base/metatags.html.twig'
                priority: 0

        'sylius_admin.base#stylesheets':
            styles:
                template: '@SyliusAdmin/shared/layout/base/stylesheets.html.twig'
                priority: 0

        'sylius_admin.base#javascripts':
            javascripts:
                template: '@SyliusAdmin/shared/layout/base/javascripts.html.twig'
                priority: 0
