.. raw:: html

    <ul class="simple">
    <li><a class="reference internal" href="installation/requirements.html"><span class="doc">System Requirements</span></a></li>
    <li><a class="reference internal" href="installation/installation.html"><span class="doc">Installation</span></a></li>
    <li><a class="reference internal plus-feature" href="installation/sylius_plus_installation.html"><span class="doc">Sylius Plus Installation</span></a></li>
    <li><a class="reference internal" href="installation/upgrading.html"><span class="doc">Upgrading</span></a></li>
    </ul>
