#!/bin/bash
bin/phpspec run -f dot

bin/behat --strict -f progress -p cached -s account
bin/behat --strict -f progress -p cached -s addressing
bin/behat --strict -f progress -p cached -s cart
bin/behat --strict -f progress -p cached -s channels
bin/behat --strict -f progress -p cached -s checkout
#bin/behat --strict -f progress -p cached -s contact (waiting for #3164)
bin/behat --strict -f progress -p cached -s currencies
bin/behat --strict -f progress -p cached -s dashboard
bin/behat --strict -f progress -p cached -s emails
bin/behat --strict -f progress -p cached -s homepage
bin/behat --strict -f progress -p cached -s i18n
bin/behat --strict -f progress -p cached -s inventory
bin/behat --strict -f progress -p cached -s localization
bin/behat --strict -f progress -p cached -s oauth
bin/behat --strict -f progress -p cached -s orders
bin/behat --strict -f progress -p cached -s payments
bin/behat --strict -f progress -p cached -s pricing
bin/behat --strict -f progress -p cached -s products
bin/behat --strict -f progress -p cached -s promotions
bin/behat --strict -f progress -p cached -s reports
bin/behat --strict -f progress -p cached -s search
bin/behat --strict -f progress -p cached -s security
bin/behat --strict -f progress -p cached -s settings
bin/behat --strict -f progress -p cached -s shipping
bin/behat --strict -f progress -p cached -s taxation
bin/behat --strict -f progress -p cached -s taxonomies
bin/behat --strict -f progress -p cached -s users
