#!/bin/bash
if [ $TRAVIS_PHP_VERSION != "7.0" ]; then bin/phpspec run -f dot; fi

bin/behat --strict -f progress -s account
bin/behat --strict -f progress -s addressing 
bin/behat --strict -f progress -s cart 
bin/behat --strict -f progress -s currencies 
bin/behat --strict -f progress -s dashboard 
bin/behat --strict -f progress -s homepage 
bin/behat --strict -f progress -s inventory 
bin/behat --strict -f progress -s localization 
bin/behat --strict -f progress -s oauth 
bin/behat --strict -f progress -s reports 
bin/behat --strict -f progress -s taxonomies 
bin/behat --strict -f progress -s users 
bin/behat --strict -f progress -s search

bin/behat --strict -f progress -s checkout features/frontend/checkout_addressing.feature
bin/behat --strict -f progress -s checkout features/frontend/checkout_finalize.feature
bin/behat --strict -f progress -s checkout features/frontend/checkout_inventory.feature
bin/behat --strict -f progress -s checkout features/frontend/checkout_payment.feature
bin/behat --strict -f progress -s checkout features/frontend/checkout_security.feature
bin/behat --strict -f progress -s checkout features/frontend/checkout_shipping.feature
bin/behat --strict -f progress -s checkout features/frontend/checkout_start.feature
bin/behat --strict -f progress -s checkout features/frontend/checkout_taxation.feature

bin/behat --strict -f progress -s checkout features/frontend/cart_taxation.feature
bin/behat --strict -f progress -s checkout features/frontend/cart_tax_categories.feature
bin/behat --strict -f progress -s checkout features/frontend/cart_inclusive_tax.feature