#!/bin/bash
bin/behat --strict -f progress -s emails
bin/behat --strict -f progress -s orders
bin/behat --strict -f progress -s payments
bin/behat --strict -f progress -s pricing
bin/behat --strict -f progress -s settings
bin/behat --strict -f progress -s shipping
bin/behat --strict -f progress -s taxation
bin/behat --strict -f progress -s i18n
bin/behat --strict -f progress -s channels

bin/behat --strict -f progress -s products features/backend/products.feature
bin/behat --strict -f progress -s products features/backend/product_attributes.feature
bin/behat --strict -f progress -s products features/backend/product_options.feature
bin/behat --strict -f progress -s products features/backend/product_archetypes.feature
bin/behat --strict -f progress -s products features/backend/product_taxonomies.feature
bin/behat --strict -f progress -s products features/backend/product_variants.feature
bin/behat --strict -f progress -s products features/backend/products_filter.feature
bin/behat --strict -f progress -s products features/frontend/products.feature

bin/behat --strict -f progress -s promotions features/backend/promotions.feature
bin/behat --strict -f progress -s promotions features/frontend/cart_promotions_complex.feature
bin/behat --strict -f progress -s promotions features/frontend/cart_promotions_coupons.feature
bin/behat --strict -f progress -s promotions features/frontend/cart_promotions_dates.feature
bin/behat --strict -f progress -s promotions features/frontend/cart_promotions_fixed.feature
bin/behat --strict -f progress -s promotions features/frontend/cart_promotions_percentage.feature
bin/behat --strict -f progress -s promotions features/frontend/cart_promotions_product.feature
bin/behat --strict -f progress -s promotions features/frontend/cart_promotions_usage_limit.feature
