#!/bin/bash

function main
{
    echo "extension = mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

    if is_cache_fresh; then
        restore_composer_lock_from_cache
    else
        install_mongodb
        store_composer_lock_in_cache
    fi
}

function install_mongodb
{
    composer require doctrine/mongodb-odm="^1.0.2"
}

function store_composer_lock_in_cache
{
    cp composer.lock $SYLIUS_CACHE_DIR/composer-mongodb.lock
    file_md5sum 'composer.lock' > $SYLIUS_CACHE_DIR/composer.lock.md5sum
}

function restore_composer_lock_from_cache
{
    cp $SYLIUS_CACHE_DIR/composer-mongodb.lock composer.lock
}

function file_md5sum
{
    md5sum $1 | awk '{ print $1 }'
}

function is_cache_fresh
{
    if [ -f $SYLIUS_CACHE_DIR/composer-mongodb.lock ] && [ -f $SYLIUS_CACHE_DIR/composer.lock.md5sum ] && [ file_md5sum 'composer.lock' -eq `cat $SYLIUS_CACHE_DIR/composer.lock.md5sum` ];
    then
        return 0
    else
        return 1
    fi
}

main
