@managing_taxons
Feature: Editing taxon's slug in multiple locales
    In order to manage access path to taxon page in many languages
    As an Administrator
    I want to be able to edit taxon's slug in multiple locales
    
    Background:
        Given the store is available in "English (United States)"
        And the store is also available in "Polish (Poland)"
        And I am logged in as an administrator

    @ui @javascript
    Scenario: Creating a root taxon with an autogenerated slug
        Given I want to create a new taxon
        When I specify its code as "MEDIEVAL_WEAPONS"
        And I name it "Medieval weapons" in "English (United States)"
        And I name it "Bronie średniowieczne" in "Polish (Poland)"
        And I add it
        Then this taxon should have slug "medieval-weapons" in "English (United States)"
        And this taxon should have slug "bronie-sredniowieczne" in "Polish (Poland)"


