* :doc:`/cookbook/promotions/custom-cart-promotion-rule`
* :doc:`/cookbook/promotions/custom-cart-promotion-action`
* :doc:`/cookbook/promotions/custom-catalog-promotion-scope`
* :doc:`/cookbook/promotions/custom-catalog-promotion-action`
* :doc:`/cookbook/promotions/catalog-promotion-labels`
* :doc:`/cookbook/promotions/catalog-promotion-performance`
* :doc:`/cookbook/promotions/custom-cart-promotion-actions-filters`
