#!/usr/bin/env bash

source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/../../../../bash/common.lib.sh"

print_header "Testing prod requirements (Composer)" "Sylius"
run_command "composer install --no-dev --no-interaction --prefer-dist"
