#!/usr/bin/env bash

source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/../../../../bash/common.lib.sh"

print_header "Testing (Behat, ~@javascript)" "Sylius"
run_command "bin/behat --strict -f progress -p cached --tags=\"~@javascript\""
if [[ $? = 1 ]]; then
    run_command "bin/behat --strict -f progress -p cached --tags=\"~@javascript\" --rerun"
fi
