#!/usr/bin/env bash

source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/../../../../bash/common.lib.sh"

prepare_for_behat_with_js() {
    # Run headless Google Chrome
    run_command "google-chrome-stable --headless --disable-gpu --no-sandbox --window-size='1680,1050' --remote-debugging-port=9222 http://localhost &"

    # Run webserver
    run_command "bin/console server:run 127.0.0.1:8080 --env=test_cached --router=app/config/router_test_cached.php --no-debug --quiet > /dev/null 2>&1 &"
}

run_behat() {
    local code=0

    print_header "Testing (Behat - brand new, javascript scenarios; @javascript && ~@todo && ~@cli)" "Sylius"
    run_command "bin/behat --strict --no-interaction -vvv -f progress -p cached --tags=\"@javascript && ~@todo && ~@cli\"" || code=$?
    if [[ ${code} = 1 ]]; then
        run_command "bin/behat --strict --no-interaction -vvv -f progress -p cached --tags=\"@javascript && ~@todo && ~@cli\" --rerun" ; code=$?
    fi

    return ${code}
}

print_header "Preparing for testing (Behat - javascript scenarios; @javascript)" "Sylius"
prepare_for_behat_with_js

run_behat
