#!/usr/bin/env bash

source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/../../../../bash/common.lib.sh"

print_header "Testing (Phpspec)" "Sylius"
run_command "bin/phpspec run --no-interaction -f dot"
