#!/usr/bin/env bash

source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/../../../../bash/common.lib.sh"

print_header "Validating (Symfony security checker)" "Sylius"
run_command "vendor/bin/security-checker security:check"
