#!/usr/bin/env bash

source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/../../../../bash/common.lib.sh"

print_header "Validating (Composer package security)" "Sylius"
run_command "bin/console security:check --end-point=http://security.sensiolabs.org/check_lock"
