#!/usr/bin/env bash

source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/../../../../bash/common.lib.sh"

print_header "Validating (DI Container)" "Sylius"

if [ "$(bin/console list | grep lint:container -c)" = 1 ]; then
    run_command "bin/console lint:container"
else
    print_info "lint:container command not found, skipped"
fi
