#!/usr/bin/env bash

source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/../../../../bash/common.lib.sh"

print_header "Validating (Doctrine schema)" "Sylius"
run_command "app/console doctrine:schema:validate --env=test_cached --no-debug -vvv"
