#!/bin/bash

EXIT_STATUS=0

bin/phpspec run -f dot || EXIT_STATUS=$?

#bin/phpunit -c app/phpunit.xml.dist || EXIT_STATUS=$?

bin/behat --suite=account -fprogress || EXIT_STATUS=$?
bin/behat --suite=addressing -fprogress || EXIT_STATUS=$?
bin/behat --suite=cart -fprogress || EXIT_STATUS=$?
bin/behat --suite=checkout -fprogress || EXIT_STATUS=$?
bin/behat --suite=currencies -fprogress || EXIT_STATUS=$?
bin/behat --suite=dashboard -fprogress || EXIT_STATUS=$?
bin/behat --suite=homepage -fprogress || EXIT_STATUS=$?
bin/behat --suite=inventory -fprogress || EXIT_STATUS=$?
bin/behat --suite=localization -fprogress || EXIT_STATUS=$?
bin/behat --suite=oauth -fprogress || EXIT_STATUS=$?

exit $EXIT_STATUS
