#!/bin/bash

EXIT_STATUS=0

bin/phpspec run -f dot || EXIT_STATUS=$?

#bin/phpunit -c app/phpunit.xml.dist || EXIT_STATUS=$?

bin/behat --suite=account -fprogress || EXIT_STATUS=$?
bin/behat --suite=addressing -fprogress || EXIT_STATUS=$?
bin/behat --suite=cart -fprogress || EXIT_STATUS=$?
bin/behat --suite=checkout features/frontend/checkout_addressing.feature -fprogress || EXIT_STATUS=$?
bin/behat --suite=checkout features/frontend/checkout_finalize.feature -fprogress || EXIT_STATUS=$?
bin/behat --suite=checkout features/frontend/checkout_inventory.feature -fprogress || EXIT_STATUS=$?
bin/behat --suite=checkout features/frontend/checkout_payment.feature -fprogress || EXIT_STATUS=$?
bin/behat --suite=checkout features/frontend/checkout_security.feature -fprogress || EXIT_STATUS=$?
bin/behat --suite=checkout features/frontend/checkout_shipping.feature -fprogress || EXIT_STATUS=$?
bin/behat --suite=checkout features/frontend/checkout_start.feature -fprogress || EXIT_STATUS=$?
bin/behat --suite=checkout features/frontend/checkout_taxation.feature -fprogress || EXIT_STATUS=$?
bin/behat --suite=currencies -fprogress || EXIT_STATUS=$?
bin/behat --suite=dashboard -fprogress || EXIT_STATUS=$?
bin/behat --suite=homepage -fprogress || EXIT_STATUS=$?
bin/behat --suite=inventory -fprogress || EXIT_STATUS=$?
bin/behat --suite=localization -fprogress || EXIT_STATUS=$?
bin/behat --suite=oauth -fprogress || EXIT_STATUS=$?

exit $EXIT_STATUS
