#!/bin/bash

EXIT_STATUS=0

bin/behat --suite=emails -fprogress || EXIT_STATUS=$?
bin/behat --suite=orders -fprogress || EXIT_STATUS=$?
bin/behat --suite=payments -fprogress || EXIT_STATUS=$?
bin/behat --suite=pricing -fprogress || EXIT_STATUS=$?
bin/behat --suite=products features/backend/products.feature -fprogress || EXIT_STATUS=$?
bin/behat --suite=products features/backend/product_attributes.feature -fprogress || EXIT_STATUS=$?
bin/behat --suite=products features/backend/product_options.feature -fprogress || EXIT_STATUS=$?
bin/behat --suite=products features/backend/product_archetypes.feature -fprogress || EXIT_STATUS=$?
bin/behat --suite=products features/backend/product_taxonomies.feature -fprogress || EXIT_STATUS=$?
bin/behat --suite=products features/backend/product_variants.feature -fprogress || EXIT_STATUS=$?
bin/behat --suite=products features/backend/products.feature -fprogress || EXIT_STATUS=$?
bin/behat --suite=products features/backend/products_filter.feature -fprogress || EXIT_STATUS=$?
bin/behat --suite=products features/frontend/products.feature -fprogress || EXIT_STATUS=$?
bin/behat --suite=promotions features/backend/promotions.feature -fprogress || EXIT_STATUS=$?
bin/behat --suite=promotions features/frontend/cart_promotions_complex.feature -fprogress || EXIT_STATUS=$?
bin/behat --suite=promotions features/frontend/cart_promotions_coupons.feature -fprogress || EXIT_STATUS=$?
bin/behat --suite=promotions features/frontend/cart_promotions_dates.feature -fprogress || EXIT_STATUS=$?
bin/behat --suite=promotions features/frontend/cart_promotions_fixed.feature -fprogress || EXIT_STATUS=$?
bin/behat --suite=promotions features/frontend/cart_promotions_percentage.feature -fprogress || EXIT_STATUS=$?
bin/behat --suite=promotions features/frontend/cart_promotions_product.feature -fprogress || EXIT_STATUS=$?
bin/behat --suite=promotions features/frontend/cart_promotions_usage_limit.feature -fprogress || EXIT_STATUS=$?
bin/behat --suite=settings -fprogress || EXIT_STATUS=$?
bin/behat --suite=shipping -fprogress || EXIT_STATUS=$?
bin/behat --suite=taxation -fprogress || EXIT_STATUS=$?
bin/behat --suite=taxonomies -fprogress || EXIT_STATUS=$?
bin/behat --suite=users -fprogress || EXIT_STATUS=$?
bin/behat --suite=search -fprogress || EXIT_STATUS=$?

bin/behat --stop-on-failure --suite=javascript || EXIT_STATUS=$?

exit $EXIT_STATUS
