#!/bin/bash

EXIT_STATUS=0

IFS=$'\n'
for command in `cat $(dirname "$0")/suites/suite-$1`
do
    if [ `echo "$command" | grep "^\s*#"` ]
    then
        continue
    fi

    echo "Running: $command"
    echo "$command" | xargs -0 /bin/bash -c || EXIT_STATUS=$?
    echo ""
done

exit $EXIT_STATUS