.. raw:: html

    <ul class="simple">
    <li><p><a class="reference internal" href="orders.html"><span class="doc">Orders</span></a></p></li>
    <li><p><a class="reference internal" href="cart-flow.html"><span class="doc">Cart flow</span></a></p></li>
    <li><p><a class="reference internal" href="taxation.html"><span class="doc">Taxation</span></a></p></li>
    <li><p><a class="reference internal" href="adjustments.html"><span class="doc">Adjustments</span></a></p></li>
    <li><p><a class="reference internal" href="promotions.html"><span class="doc">Promotions</span></a></p></li>
    <li><p><a class="reference internal" href="coupons.html"><span class="doc">Coupons</span></a></p></li>
    <li><p><a class="reference internal" href="payments.html"><span class="doc">Payments</span></a></p></li>
    <li><p><a class="reference internal" href="invoices.html"><span class="doc">Invoices</span></a></p></li>
    <li><p><a class="reference internal" href="shipments.html"><span class="doc">Shipments</span></a></p></li>
    <li><p><a class="reference internal" href="checkout.html"><span class="doc">Checkout</span></a></p></li>
    <li><p><a class="reference internal plus-feature" href="returns.html"><span class="doc">Returns</span></a></p></li>
    <li><p><a class="reference internal" href="refunds.html"><span class="doc">Refunds</span></a></p></li>
    </ul>
