* **Code**

  * :doc:`Bugs </contributing/code/bugs>`
  * :doc:`Patches </contributing/code/patches>`
  * :doc:`Security </contributing/code/security>`
  * :doc:`Behavior Driven Development </contributing/code/bdd>`
  * :doc:`Coding Standards</contributing/code/standards>`
  * :doc:`Code Conventions</contributing/code/conventions>`
  * :doc:`Git</contributing/code/git>`
  * :doc:`License </contributing/code/license>`

* **Documentation**

  * :doc:`Overview </contributing/documentation/overview>`
  * :doc:`Format </contributing/documentation/format>`
  * :doc:`Documentation Standards </contributing/documentation/standards>`
  * :doc:`License </contributing/documentation/license>`

* **Community**

  * :doc:`Support </contributing/community/support>`
  * :doc:`Statistics </contributing/community/stats>`
