sylius_twig_hooks:
    hooks:
        'sylius_shop.account.resend_verification_email':
            content:
                template: '@SyliusShop/account/resend_verification_email/content.html.twig'
                priority: 0

        'sylius_shop.account.resend_verification_email.content':
            form_container:
                template: '@SyliusShop/account/resend_verification_email/content/form_container.html.twig'
                priority: 0

        'sylius_shop.account.resend_verification_email.content.form_container':
            header:
                template: '@SyliusShop/account/resend_verification_email/content/form_container/header.html.twig'
                priority: 200
            description:
                template: '@SyliusShop/account/resend_verification_email/content/form_container/description.html.twig'
                priority: 100
            form:
                template: '@SyliusShop/account/resend_verification_email/content/form_container/form.html.twig'
                priority: 0

        'sylius_shop.account.resend_verification_email.content.form_container.form':
            email:
                template: '@SyliusShop/account/resend_verification_email/content/form_container/form/email.html.twig'
                priority: 100
            submit:
                template: '@SyliusShop/account/resend_verification_email/content/form_container/form/submit.html.twig'
                priority: 0
