* **Code**:

  * :doc:`Bugs </contributing/code/bugs>`
  * :doc:`Patches </contributing/code/patches>`
  * :doc:`Community </contributing/community/index>`
  * `Coding Standards <http://symfony.com/doc/current/contributing/code/standards.html>`_
  * `Code Conventions <http://symfony.com/doc/current/contributing/code/conventions.html>`_
  * :doc:`License </contributing/code/license>`

* **Documentation**:

  * :doc:`License </contributing/documentation/license>`
