name: Bunnyshell - Cleanup Preview Environments
concurrency: bns-cleanup
on:
  workflow_dispatch: ~
  schedule:
    - cron: '* 6 * * *'
permissions:
  pull-requests: read

jobs:
  cleanup:
    name: Cleanup Bunnyshell Environments
    uses: bunnyshell/workflows/.github/workflows/cleanup-envs.yaml@v2
    with:
      project-id: ${{ vars.BUNNYSHELL_PROJECT_ID }}
      include-not-found: true
    secrets:
      bunnyshell-access-token: ${{ secrets.BUNNYSHELL_ACCESS_TOKEN }}
