name: Bunnyshell - Prepare Preview Environment Configuration
on:
    pull_request:
        types: [ opened, reopened, synchronize ]
        branches:
            - '*'
        paths-ignore:
            - "*.md"
    issue_comment:
        types: [ created, edited ]
permissions:
    contents: read
    pull-requests: write

jobs:
    deploy:
        name: Deploy Environment
        uses: bunnyshell/workflows/.github/workflows/prepare-configuration.yaml@eb12a4d9154db124044f2d155e2495bf295b18c7 # v2.2.0
        with:
            bunnyshell-yaml-path: .bunnyshell/templates/preview/bunnyshell.yaml
            allowed-users: ${{ vars.BUNNYSHELL_ALLOWED_USERS }}
            git-ref: refs/pull/${{ github.event.number || github.event.issue.number }}/head
            restricted-files: |
                .bunnyshell/*
